version: '3.8'
services:
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    restart: unless-stopped
  server:
    build: ./server
    ports:
      - '5000:5000'
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis