services:
  # Static Site for the client
  - type: web
    name: subtrax-client
    runtime: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/build

  # Web Service for the server (API)
  - type: web
    name: subtrax-server
    runtime: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_BASE64
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: REDIS_URL
        sync: false