name: Secret scanning (gitleaks)

on:
  push:
    branches: [ main, master, 'feat/**' ]
  pull_request:
    branches: [ main, master ]

jobs:
  gitleaks:
    name: Scan for secrets with gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run gitleaks
        uses: zricethezav/gitleaks-action@v2
        with:
          args: '--redact --report-path=.gitleaks-report'

      - name: Upload gitleaks report (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: .gitleaks-report
