name: CI Smoke

on:
  push:
    branches: [ main, feat/frontend-host-agnostic ]
  pull_request:
    branches: [ main ]

jobs:
  server-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install server deps
        working-directory: ./server
        run: npm ci
      - name: Run server tests
        working-directory: ./server
        run: npm test --silent
  smoke-health:
    runs-on: ubuntu-latest
    needs: server-tests
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install server deps
        working-directory: ./server
        run: npm ci
      - name: Start server in background
        working-directory: ./server
        run: |
          nohup node server.js > server.log 2>&1 &
          sleep 2
      - name: Health check
        working-directory: ./server
        run: |
          curl --fail http://127.0.0.1:5000/api/health

  smoke-firebase-init:
    runs-on: ubuntu-latest
    needs: server-tests
    # only run if we have at least one of the firebase secrets configured in repo secrets
    if: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 || (secrets.FIREBASE_SECRET_NAME && secrets.FIREBASE_PROJECT_ID) }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install server deps
        working-directory: ./server
        run: npm ci
      - name: Prepare env from secrets
        working-directory: ./server
        run: |
          echo "Preparing env..."
          if [ -z "$FIREBASE_SERVICE_ACCOUNT_BASE64" ] && [ -z "$FIREBASE_SECRET_NAME" ] && [ -z "$FIREBASE_PROJECT_ID" ]; then
            echo "WARNING: No Firebase secrets set. Skipping Firebase init."
          fi
        env:
          FIREBASE_SERVICE_ACCOUNT_BASE64: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}
          FIREBASE_SECRET_NAME: ${{ secrets.FIREBASE_SECRET_NAME }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      - name: Optionally fetch secret from GCP Secret Manager
        if: ${{ secrets.GCP_SA_KEY && secrets.FIREBASE_PROJECT_ID }}
        working-directory: ./server
        run: |
          echo "Authing with provided GCP_SA_KEY and pulling secret..."
          echo "${{ secrets.GCP_SA_KEY }}" > /tmp/sa.json
          curl -sSLo /tmp/install_gcloud.sh https://sdk.cloud.google.com
          # Use google-github-actions/setup-gcloud normally, but keep this fat fallback in case it's not present
          apt-get update && apt-get install -y --no-install-recommends python3 python3-apt ca-certificates gnupg
          # Authenticate and pull secret
          gcloud auth activate-service-account --key-file=/tmp/sa.json
          gcloud config set project "$FIREBASE_PROJECT_ID"
          SECRET_NAME="${FIREBASE_SECRET_NAME:-firebase-service-account}"
          gcloud secrets versions access latest --secret="$SECRET_NAME" > /tmp/firebase.json
          export FIREBASE_SERVICE_ACCOUNT_JSON=$(cat /tmp/firebase.json)
          echo "Pulled secret into FIREBASE_SERVICE_ACCOUNT_JSON"
        working-directory: ./server
      - name: Run firebase init smoke check
        working-directory: ./server
        run: node ./scripts/checkFirebaseInit.js

  integration-tests-with-redis:
    runs-on: ubuntu-latest
    needs: server-tests
    services:
      redis:
        image: redis:7.2
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install server deps
        working-directory: ./server
        run: npm ci
      - name: Run integration tests with Redis available
        working-directory: ./server
        env:
          REDIS_URL: redis://127.0.0.1:6379
        run: |
          echo "Waiting for redis service..."
          sleep 5
          npm test --silent
